export const projects = [
  {
    number: 4,
    type: "Website",
    title: "Magic: The Gathering Cards",
    description: "This project is a sophisticated web page designed to provide detailed information about Magic: The Gathering cards by consuming the Magic: The Gathering API. Built with Next.js, the application features a sleek and responsive design. It includes a powerful search bar for quick card lookups, lazy loading to enhance performance and user experience, and an integrated bot to answer questions about the game. ",
    image: "/images/projects/project-4-mtg.PNG",
    githubURL: "https://github.com/rozuke/mtg-cards-page",
    websiteURL: "https://mtg-cards-page.vercel.app/",
  },
  {
    number: 7,
    type: "Backend App",
    title: "WhatsApp Chatbot",
    description: "This project is developed using the Meta API and Dialogflow CX, integrated with a backend built in Spring Boot and MongoDB for data persistence. The chatbot leverages Dialogflow CX for advanced conversational capabilities, providing users with a responsive and intelligent interaction experience.",
    image: "/images/projects/project-7-chatbot.PNG",
    githubURL: "https://github.com/rozuke/whatsapp-chatbot-spring-boot",
  },
  {
    number: 2,
    type: "Website",
    title: "Website for a motorcycle agency",
    description: "The frontend seamlessly integrates with a backend REST API developed using Spring Boot, ensuring efficient data retrieval and interaction.",
    image: "/images/projects/project-2-chinmoto.PNG",
    githubURL: "https://github.com/rozuke/chinmoto-ui",
    websiteURL: "https://chinmoto-ui.vercel.app/",
  },
  {
    number: 1,
    type: "REST API",
    title: "API for my Dota 2 matches",
    description: "The application is containerized with Docker, ensuring seamless deployment and environment consistency. To guarantee reliability and correctness, comprehensive testing is implemented using Testcontainers, allowing for integration tests with real database instances. ",
    image: "/images/projects/project-1-hero-api.PNG",
    githubURL: "https://github.com/rozuke/dota2-matches-rest-api",
  },
  {
    number: 5,
    type: "Mobile App",
    title: "English learning application",
    description: "This project is a mobile application developed using Flutter, forming a crucial part of a comprehensive platform that also includes a web application. The platform is built with a microservice architecture, ensuring scalability, flexibility, and efficient management of different services.",
    image: "/images/projects/project-5-eiemobapp.png",
    githubURL: "https://github.com/rozuke/eie-mobile-app",
  },
  {
    number: 6,
    type: "Web App",
    title: "English learning web application",
    description: "This project is a web application that forms an integral part of a platform designed with a microservice architecture. The web app is built with Next.js",
    image: "/images/projects/project-6-eieweb.png",
    githubURL: "https://github.com/rozuke/eie-web-app",
  },
  {
    number: 3,
    type: "Desktop App",
    title: "Currency converter",
    description: "This project is a visually appealing currency converter application developed with JavaFX. The application dynamically updates currency values by integrating with an external API, ensuring accurate and up-to-date exchange rates. ",
    image: "/images/projects/project-3-conversor.PNG",
    githubURL: "https://github.com/rozuke/alura-conversor",
  },
  
];
